Repository hafid-Qa/yochien-connect, pull requests merged in 2022-12, with the labels that each got.

#1 Added test accounts to the seeds
  db/seeds.rb
Labels: enhancement

#4 Just adding the fix to gemfile.lock
  Gemfile.lock
Labels: bug, Security

#6 Added the Children controller and their views.
  app/controllers/children_controller.rb
  app/views/children/index.html.erb
  config/routes.rb
  test/controllers/children_controller_test.rb
Labels: enhancement

#7 Added the controller for messages
  app/controllers/messages_controller.rb
  test/controllers/messages_controller_test.rb
Labels: enhancement

#17 Rename column children
  Gemfile
  Gemfile.lock
  app/javascript/front_end/components/App.jsx
  app/javascript/front_end/components/Child.jsx
  app/javascript/front_end/components/Children.jsx
  app/javascript/front_end/index.jsx
  app/models/child.rb
  app/views/children/index.html.erb
  db/migrate/20221216112419_add_qr_code_to_children.rb
  db/migrate/20221216130250_add_date_of_birth_to_children.rb
  db/migrate/20221217011125_rename_day_of_birth_to_birthday_in_children.rb
  db/schema.rb
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#19 Fix error in react config
  Gemfile
  Gemfile.lock
  app/javascript/front_end/components/Child.jsx
  app/javascript/front_end/components/Children.jsx
  app/models/user.rb
  db/migrate/20221217054634_rename_type_to_role_type_in_users.rb
  db/schema.rb
  db/seeds.rb
Labels: bug, enhancement

#20 fix useState and useEffect for children
  app/assets/stylesheets/components/_child.scss
  app/javascript/front_end/components/Children.jsx
  app/javascript/front_end/mockData/data.js
Labels: bug
